### ISSUE TITLE
rosbag seems inaccessible

### ISSUE THREAD

**Issue by libing64** [vectr-ucla/direct_lidar_odometry#1]
The rosbag seems inaccessible, would you like to share another link for downloading?

**Comment by kennyjchen** [comment]
Hi @libing64 -- could you please post a screenshot or elaborate on the symptoms? The download link is still working for me. FYI the file is hosted on Box.

**Comment by narutojxl** [comment]
With a vpn in china mainland can  download, otherwise can not.

**Comment by libing64** [comment]
> Hi @libing64 -- could you please post a screenshot or elaborate on the symptoms? The download link is still working for me. FYI the file is hosted on Box.

@kennyjchen 
![Screenshot from 2021-12-03 09-47-53](https://user-images.githubusercontent.com/3192355/144530830-894f5a2c-bd75-4204-9c8f-8e181495b217.png)
![Screenshot from 2021-12-03 09-44-42](https://user-images.githubusercontent.com/3192355/144530832-9e6b3ee0-2410-4473-b178-fa614b74613a.png)

**Comment by libing64** [comment]
> With a vpn in china mainland can download, otherwise can not.

@narutojxl My network has access to foreign networks and I could use goolge/youtube normally.

**Comment by narutojxl** [comment]
It's werid, i don't know whether it is Box internet stability. I can download now, but sometimes can not. Maybe google drive is stable ?
![image](https://user-images.githubusercontent.com/6205343/144539974-74960fec-231a-445c-8ab8-2b19bd304542.png)

**Comment by libing64** [comment]
The bag could be download with my home network and a vpn, great thanks for your sharing.

**Comment by 2653888596** [comment]
> The bag could be download with my home network and a vpn, great thanks for your sharing.

Hello, could you please put this rosbag onto BaiDuYun? I will very appreciate. Thank U
