### ISSUE TITLE
jacobian 

### ISSUE THREAD

**Issue by narutojxl** [vectr-ucla/direct_lidar_odometry#10]
Hello author,
I want to derive the jacobian in the code. I see we use [global perturbation](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/include/nano_gicp/impl/lsq_registration_impl.hpp#L179) to update.  When i try this, i meet this problem to look for your help.
![image](https://user-images.githubusercontent.com/6205343/162926545-f84dfe89-4c96-4348-b9b1-07b7268ff70b.png)
When using [Woodbury matrix identity](https://en.wikipedia.org/wiki/Woodbury_matrix_identity) it seems to make the formula more complicated, so i'm stuck to look for your help. Thanks for your help in advance!

Best regards
Xiaoliang jiao

**Comment by kennyjchen** [comment]
Hi @narutojxl --

Thanks for the interest. Unfortunately we're only here to help with the code, but there are some wonderful resources you can find online to help you with the derivation. Also, since we use a modified version of the `fast_gicp` solver, we also recommend referring back to a similar [issue](https://github.com/SMRT-AIST/fast_gicp/issues/20) you opened on their repository a few years ago. Best of luck.

**Comment by narutojxl** [comment]
Thanks author for remainding me that issue, i have forgot it :) .  As the author told calculating the jacobian of $M^{-1}$ wrt R is very  [complicated, slow and impractical.](https://github.com/SMRT-AIST/fast_gicp/issues/20#issuecomment-664198521),  so we approximate it as a constant matrix during each optimization iteration step. 
When i carefully expand my derivation as the following, it seems not equal in the code mathematically, [hessian Hi and bi](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/include/nano_gicp/impl/nano_gicp_impl.hpp#L253-L254),  [LM llt solver](https://github.com/vectr-ucla/direct_lidar_odometry/blob/master/include/nano_gicp/impl/lsq_registration_impl.hpp#L172-L173) ?
![image](https://user-images.githubusercontent.com/6205343/163126426-7a26c8fd-26a5-4b13-bc9a-84f8d96d909c.png)

**Comment by kennyjchen** [comment]
I would recommend asking the `fast_gicp` authors, as we inherited that part of the code from them.

**Comment by narutojxl** [comment]
Hello  doctor Koide, @koide3
If you are interested in this issue and have some time, could you please give some advice about why not calculate hessian like the above mentioned form? Thanks for your help and time in advance!

**Comment by koide3** [comment]
The GICP cost is given by <img src="https://render.githubusercontent.com/render/math?math=r = d^T M^{-1} d">. To use the Gauss-Newton method, we need <img src="https://render.githubusercontent.com/render/math?math=\partial d/\partial T"> (not <img src="https://render.githubusercontent.com/render/math?math=\partial r / \partial T">) and weighting it by <img src="https://render.githubusercontent.com/render/math?math=M^{-1}">. So, <img src="https://render.githubusercontent.com/render/math?math=J = \partial d / \partial T">, and H is given as <img src="https://render.githubusercontent.com/render/math?math=J^T M^{-1} J">.

Eqs. 4 and 10 in the following paper would help to understand how the information matrix (the matrix <img src="https://render.githubusercontent.com/render/math?math=M^{-1}"> in our case) is computed and used for the Gauss-Newton method: http://www2.informatik.uni-freiburg.de/~stachnis/pdf/grisetti10titsmag.pdf

**Comment by narutojxl** [comment]
Thanks Dr @koide3 and @kennyjchen  for your kind and patient reply.
