### ISSUE TITLE
Map generation

### ISSUE THREAD

**Issue by Srichitra-S** [vectr-ucla/direct_lidar_odometry#14]
Hi,
How is the map generated? What algorithm is used? Can we upload a pcd map of the environment and then apply dlo just for localisation?
I assumed dlo as a localisation algorithm, but it seems to take in the point cloud data from the bag file and generate a map on its own.

**Comment by kennyjchen** [comment]
Hi @Srichitra-S -- DLO is an odometry algorithm and generates both pose (6DOF) and map, which is represented by a set of keyed scans throughout the environment. The algorithm currently doesn't support pure localization on a provided map, but this should be pretty straightforward to implement for those who are interested. Note that depending on the map size and complexity, an initial pose may be required. See my comment here for more information: #11

**Comment by JACKLiuDay** [comment]
> Hi @Srichitra-S -- DLO is an odometry algorithm and generates both pose (6DOF) and map, which is represented by a set of keyed scans throughout the environment. The algorithm currently doesn't support pure localization on a provided map, but this should be pretty straightforward to implement for those who are interested. Note that depending on the map size and complexity, an initial pose may be required. See my comment here for more information: #11

Hi, thank you for your great work. Does DLO have a map saving function, such as saving in pcd format?

**Comment by kennyjchen** [comment]
Hi @JACKLiuDay --

We've added a new service to save DLO's generated map into a `.pcd` in [`v1.4.0`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.0) per your request. To use it, please call the following command in a separate terminal window:

```
rosservice call /robot/dlo_map/save_pcd LEAF_SIZE SAVE_PATH
```

**Comment by JACKLiuDay** [comment]
> Hi @JACKLiuDay --
> 
> We've added a new service to save DLO's generated map into a `.pcd` in [`v1.4.0`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.0) per your request. To use it, please call the following command in a separate terminal window:
> 
> ```
> rosservice call /robot/dlo_map/save_pcd LEAF_SIZE SAVE_PATH
> ```

Wow, it's awesome! Thank you for great work! We will test it soon.

**Comment by HomieRegina** [comment]
Hi, I have successfully run through the dataset named dlo_test.bag. But I still can't save successfully .pcb file. The following picture is my running result.
![image](https://user-images.githubusercontent.com/107244263/175879419-f3ac410f-49a0-4334-ac82-7a038d466f01.png)
Could you please tell me how to deal this issue? Looking forward to your reply.

**Comment by HomieRegina** [comment]
> 

Hi, I have successfully run through the dataset named dlo_test.bag. But I still can't save successfully .pcb file. The following picture is my running result. 
![图片](https://user-images.githubusercontent.com/107244263/175850027-a7551d15-137e-4a64-a314-2283b9c9919c.png)
Could you please tell me how to deal this issue? Looking forward to your reply.

**Comment by HomieRegina** [comment]
> Hi @JACKLiuDay --
> 
> We've added a new service to save DLO's generated map into a `.pcd` in [`v1.4.0`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.0) per your request. To use it, please call the following command in a separate terminal window:
> 
> ```
> rosservice call /robot/dlo_map/save_pcd LEAF_SIZE SAVE_PATH
> ```

By the way, do you have the dataset of the second video in License in README.md? We want to try that dataset. Could you please share it with us?

**Comment by kennyjchen** [comment]
Hi @HomieRegina -- don't forget to change the input arguments of the service call, e.g.
```
rosservice call /robot/dlo_map/save_pcd 0.25 ~/Downloads
```

Regarding the multilevel dataset, we'll need to look into if we can publicly share that or not. Thanks.

**Comment by HomieRegina** [comment]
> Hi @HomieRegina -- don't forget to change the input arguments of the service call, e.g.
> 
> ```
> rosservice call /robot/dlo_map/save_pcd 0.25 ~/Downloads
> ```
> 
> Regarding the multilevel dataset, we'll need to look into if we can publicly share that or not. Thanks.

Thank you for your reply. But now I have a new problem. When I ran dlo_ test. bag yesterday, rviz can successfully display the map. However, it was not displayed when running today. I tried so many times and the program did not report an error.
![图片](https://user-images.githubusercontent.com/107244263/176081449-7ece62aa-74a9-4857-afdf-c014a3eb7ebb.png)
Do you know the reason and how to solve it?

**Comment by kennyjchen** [comment]
Might be a topic name mismatch if you modified the launch file. Try double-checking that.
