### ISSUE TITLE
Hardware architecture

### ISSUE THREAD

**Issue by HomieRegina** [vectr-ucla/direct_lidar_odometry#16]
Hi. I have a NVIDIA NX board, which is based on ARM architecture. I encountered the following problems when compiling on the NX board.
![图片](https://user-images.githubusercontent.com/107244263/176587054-7a8a3cf5-418e-4f66-9039-8a0c76abcc3e.png)

Can this package run under arm architecture? Is this error related to the architecture? How to solve this issue?

**Comment by kennyjchen** [comment]
Hi @HomieRegina -- yes, this was something we also saw during our internal tests on a Raspberry Pi (also ARM). ARM-based boards apparently do not have the `cpuid.h` system header file.

We've released a patch in [`v1.4.1`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.1) which should fix this.

**Comment by HomieRegina** [comment]
> Hi @HomieRegina -- yes, this was something we also saw during our internal tests on a Raspberry Pi (also ARM). ARM-based boards apparently do not have the `cpuid.h` system header file.
> 
> We've released a patch in [`v1.4.1`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.1) which should fix this.

Thanks for your great work. We will test it soon.
