### ISSUE TITLE
HI, I use the nanoicp to location, but it cann`t work

### ISSUE THREAD

**Issue by tust13018211** [vectr-ucla/direct_lidar_odometry#17]
Thanks for your  work, I want to use nanoicp to location, it cann`t work right, but I use the pcl Gicp， it can work,  so, there is anything i need to do?

**Comment by tust13018211** [comment]
I found that the translation grows fast，it seems strangeness

**Comment by kennyjchen** [comment]
Hi @tust13018211 -- are you using NanoGICP as part of DLO or outside of this package? Thanks.

**Comment by tust13018211** [comment]
I  try  to use in dlo and outside , all the result is not good

**Comment by tust13018211** [comment]
![2683AD2C-796C-467e-AB48-928145A2D596](https://user-images.githubusercontent.com/83019441/176983205-fffd105c-c39a-4a00-af12-760261f96f1a.png)
![DE3EE3FE-E199-4e91-BE6F-54DDF390EB3E](https://user-images.githubusercontent.com/83019441/176983214-fab779ae-a176-4f65-805c-773c1fc3e0f1.png)

**Comment by kennyjchen** [comment]
Are covariances and/or kdtrees of both clouds being properly set in your code?

**Comment by tust13018211** [comment]
Convariances is ok， but kdtree  i do not konwn how to do properly for map .  i want to know kdtree and convariance is both need,  and how to set this for map

**Comment by tust13018211** [comment]
is there any pronlem above ?

**Comment by tust13018211** [comment]
at first, I use the
m_iGicpScanToMap_.setInputTarget(map);
m_iGicpScanToMap_.calculateTargetCovariances();
to built target cloude Covariances and kdtree, and then
m_iGicpScanToMap_.setInputSource(m_pCurrentScan_);
m_iGicpScanToMap_.calculateSourceCovariance
use this to built source cloude Covariances and kdtree, at last,
m_iGicpScanToMap_.align(*aligned, init_pose.matrix.cast());

is there any pronlem above ?

**Comment by kennyjchen** [comment]
Hmm looks fine to me. Just to clarify: does DLO work on your end (without any modifications)? And in your code above, switching out NanoGICP with PCL's GICP works? The package should work as a replacement for PCL's GICP (sans some of the computational benefits from data structure recycling). A bit hard to help debug without more information.

**Comment by tust13018211** [comment]
Thaks your reply, I just want to test nanogicp for location with a map, I adjust the parameter, it seems work. the result in the picture,  the result seems not very good 
![1D738FC8-04F3-412a-A4BE-B35AC7B824A7](https://user-images.githubusercontent.com/83019441/177537592-0d44fb4c-a506-4490-bcdf-60c80e88923a.png)

**Comment by tust13018211** [comment]
Thaks your reply, I just want to test nanogicp for location with a map, I adjust the parameter, it seems work. the result in the picture, the result seems not very good
![1D738FC8-04F3-412a-A4BE-B35AC7B824A7](https://user-images.githubusercontent.com/83019441/177538322-48bfda7d-46f1-45fa-bbd4-d8c2c507ecab.png)

**Comment by tust13018211** [comment]
Thaks your reply, I just want to test nanogicp for location with a map, I adjust the parameter, it seems work. the result in the picture, the result seems not very good
![11](https://user-images.githubusercontent.com/83019441/177538488-57bf2bf8-762b-4af2-8384-87b90c4215da.png)

**Comment by kennyjchen** [comment]
Oh I see. Unfortunately we have not tested DLO (or NanoGICP) for localization with a provided map (as mentioned [here](https://github.com/vectr-ucla/direct_lidar_odometry/issues/14) and [here](https://github.com/vectr-ucla/direct_lidar_odometry/issues/11)) and assumes no prior knowledge of the environment, so your results may vary.
