### ISSUE TITLE
How to correct point cloud caused by motion？

### ISSUE THREAD

**Issue by JACKLiuDay** [vectr-ucla/direct_lidar_odometry#22]
Hi, thank you for your great work about DLO. I have a question. When the robot is moving fast, the lidar point cloud will generate distortion due to movement, which will cause negative impact on the construction of the map. So how did DLO deal with this problem?

**Comment by kennyjchen** [comment]
DLO does not correct for motion distortion and assumes that either the scan is deskewed by an upstream module, or that the effect is negligible due to low movement speeds or a high sensor rate.

**Comment by JACKLiuDay** [comment]
> DLO does not correct for motion distortion and assumes that either the scan is deskewed by an upstream module, or that the effect is negligible due to low movement speeds or a high sensor rate.

Thank you for your reply.
