### ISSUE TITLE
a little problem

### ISSUE THREAD

**Issue by AFEICHINA** [vectr-ucla/direct_lidar_odometry#28]
Hi Author,
    I just wanted to let you know that I truly appreciate your work. It has been useful, and it's also very simple and easy to extend. Thank you for making it open source.
    However, I did notice a small small small bug in the function pushSubmapIndices() when running in Debug mode. If dists is empty, pq.top() becomes unreachable. In Release mode, the compiler can fix this issue. Perhaps it would be possible to add some code to avoid this problem altogether?
   Best regards.
   Afei

**Comment by kennyjchen** [comment]
Hi @AFEICHINA -- great catch! I added a quick check on `dists` in [`v1.4.3`](https://github.com/vectr-ucla/direct_lidar_odometry/releases/tag/v1.4.3) which should address it. Thanks for letting us know about this bug and for using our work. Let me know if that fixes it for you.
