### ISSUE TITLE
Initialization function

### ISSUE THREAD

**Issue by numb0824** [vectr-ucla/direct_lidar_odometry#33]
Hi，
     Thanks for your great work！ I have been testing 'DLO' for a long time and its performance is excellent .
     In some tests, due to environmental reasons such as a particularly sparse environment, DLO results are incorrect. Of course, this is not a problem for 'DLO' itself. When this situation occurs, I don't want to shut down DLO and restart it, but rather want to initialize it, just like the initialpose function in ROS.
    So could you please add features like "initialpose" to 'DLO' to solve the problem of not turning off 'DLO' and continuing to run in case of inaccurate pose caused by accidents?
    I apologize to you if my request is very presumptuous.
     Thank you again for your great work .

Best wishes

**Comment by kennyjchen** [comment]
Hi @numb0824 -- thanks for using our work. Do you mean just re-initializing the pose? Or perhaps a complete reset of DLO?

**Comment by numb0824** [comment]
> Hi @numb0824 -- thanks for using our work. Do you mean just re-initializing the pose? Or perhaps a complete reset of DLO?
Hi,@kennyjchen -- thanks fou your reply!
      I want to completely reset DLO without shutting it down.

Sincere thanks again for your great work

**Comment by wienans** [comment]
Hi @kennyjchen 
actually that would be a nice feature, to reset the Process easily without killing the launch file.

**Comment by kennyjchen** [comment]
Hmm... I'll have to think about this. It's a bit tricky since DLO has separate nodes for odometry and mapping. In the meanwhile, we welcome any PR's to add this functionality!
