### ISSUE TITLE
Parameter tuning suggestions

### ISSUE THREAD

**Issue by JereKnuutinen** [vectr-ucla/direct_lidar_odometry#35]
I am doing research related to motion based calibration and I am using DLO for lidar odometry generation. It has worked fine so far but with my current dataset it gives non reasonable pose estimates, what are the first parameters try to tune? Figure below shows some things related to my dataset. So it is infinity shape path in a planar ground.
![googlemaps_fig](https://github.com/vectr-ucla/direct_lidar_odometry/assets/107494064/62991d38-e4c1-48f7-9b13-3f58b793949d)

sample pointclouds are like figure below. I have combined two vlp16 point clouds:
![sample_pointcloud](https://github.com/vectr-ucla/direct_lidar_odometry/assets/107494064/83a15f79-f257-4d1a-8529-bee09cdcba74)

**Comment by kennyjchen** [comment]
Hi @JereKnuutinen -- thanks for using our work. I'll need more information about your dataset and how the pose estimates are not reasonable (or a sample bag). Is it jittery, or does localization not work altogether? Are you using LiDAR only or do you also have an IMU?

As for some parameters you can try tuning, check out [this issue](https://github.com/vectr-ucla/direct_lidar_odometry/issues/27). Let me know if that helps!

**Comment by JereKnuutinen** [comment]
Hi, thanks for your reply! I am not using IMU only combined pointcloud from two vlp 16 lidar sensors. Here is a rosbag if you want to take a look. Also parameters from previous issue do not worked.

https://drive.google.com/file/d/1I2svjYyjBIBrcEF_-biIWNRh4FgDZllM/view?usp=sharing

Topic name is \merged_pc

**Comment by kennyjchen** [comment]
Have you tried it using just one point cloud (without merging)? How does that look?

**Comment by kennyjchen** [comment]
Ah -- I see the problem after playing with the data you sent. Two issues:
- There are multiple points on the body of the robot (car?), which can cause issues in scan-matching

![image](https://github.com/vectr-ucla/direct_lidar_odometry/assets/7662578/3da5fd5b-c3bf-45fb-b649-1d8254092c06)


- You're using a very sparse, long-range LiDAR. So the current scan-to-map GICP threshold is too small for that (converges to a local minima)

Try the following:
- Set `cropBoxFilter: size` to `10` (or some value to get rid points on your platform) in `params.yaml`
- Set `gicp: s2m: maxCorrespondenceDistance` to `10` (play around with this) in `params.yaml`

![image](https://github.com/vectr-ucla/direct_lidar_odometry/assets/7662578/7f15a655-c7c8-40a5-9fa5-76218f866611)

Let me know if that works.

**Comment by JereKnuutinen** [comment]
Thank you very much for your help, it seems to be working now!

**Comment by kennyjchen** [comment]
Nice! Glad to hear that.
