### ISSUE TITLE
Nano-GICP branch

### ISSUE THREAD

**Issue by engcang** [vectr-ucla/direct_lidar_odometry#39]
Hi. Thank you for sharing the great work.

I made a Nano-GICP only repository to be used as a module in other packages as [here](https://github.com/engcang/nano_gicp).
If you can create a new separate branch for it, I'd love to push this branch via pull request, if you like it.
(Otherwise, I cannot open a pull request to a new branch from my end)

With the module branch, Nano-GICP can be easily imported and used as follows:
[CMakeLists.txt](https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/CMakeLists.txt#L31)
[Header](https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/include/main.h#L36-L38)
[Method](https://github.com/engcang/FAST-LIO-SAM-QN/blob/master/fast_lio_sam_qn/src/methods.cpp#L88-L93)
Or, simply as explained in [here](https://github.com/engcang/nano_gicp#use-case)

**Comment by kennyjchen** [comment]
Amazing -- this looks great! I've made a new branch [here](https://github.com/vectr-ucla/direct_lidar_odometry/tree/nano_gicp), which you can PR to. Thanks so much @engcang for the contribution :^)
