### ISSUE TITLE
the transformation between your lidar and imu?

### ISSUE THREAD

**Issue by nonlinear1** [vectr-ucla/direct_lidar_odometry#4]
I use a vlp16 lidar and a microstran imu(3DM-GX5-25) to run your program. But I failed. I think my transformation between imu and lidar is different from yours. So could you tell your true transformation between imu and lidar. the following pitcure is my configuration:
![453670779](https://user-images.githubusercontent.com/19766939/148742538-43397e19-5e81-4e3f-a492-7120891dacb2.jpg)
Thank you very much!

**Comment by kennyjchen** [comment]
Hi @nonlinear1, could you elaborate a bit on how it's failing? Could you try disabling the IMU by setting ```imu: false``` in ```cfg/dlo.yaml```?

**Comment by nonlinear1** [comment]
Thank you for your help! I have set imu: false in cfg/dlo.yaml adopting your suggestion. But I still 
failed . see the following pictures


![1861169299](https://user-images.githubusercontent.com/19766939/148861012-06dd6a23-3582-4b78-908a-5adec48ef51c.jpg)
![715083198](https://user-images.githubusercontent.com/19766939/148861020-e4832ab0-1b9b-423d-97ff-e224f636a518.jpg)

![759034718](https://user-images.githubusercontent.com/19766939/148861027-f7ce6f21-db60-40f5-8f61-f3df1edbfa7b.jpg)

**Comment by kennyjchen** [comment]
Lol yeah that definitely doesn't look right. Does it work with the test bag? I see that you're on v1.0.0; can you try using the latest code on the `master` branch? And can you record me a bag with your own data so I can help debug?

**Comment by nonlinear1** [comment]
Thank you very much! I solve the problem.  I change the configuration of my vlp16. Your slam is very good! 
![536124077](https://user-images.githubusercontent.com/19766939/148875805-95d233c4-1319-44c3-8952-4942c68da51a.jpg)

**Comment by nonlinear1** [comment]
I solve this problem. I change my vlp16 configuration and I got the good result

**Comment by kennyjchen** [comment]
Nice! Glad to hear that.
