### ISSUE TITLE
Loop closure 

### ISSUE THREAD

**Issue by wienans** [vectr-ucla/direct_lidar_odometry#41]
Hey this is more of a question than a issue.
I wanted to ask if your system does any kind of Loop closure to make sure that for big maps where you revisit a certain location after a time the drift of the map is minimal.

As in the videos or GIFs we never see a "drifted" map which gets visually corrected, but all maps look very precise i was wondering if the algorithms drift is that small or if there is some loop closure happening.

Greetings and thanks for the great work
Sven

**Comment by kennyjchen** [comment]
Hi @wienans -- DLO is purely an odometry algorithm and doesn't contain any explicit loop closures for retroactive map correction.

**Comment by wienans** [comment]
Okay thanks for info :)
