### ISSUE TITLE
Usage of LIDAR intensities

### ISSUE THREAD

**Issue by LotfiZ** [vectr-ucla/direct_lidar_odometry#42]
Hi, 

First, congrats for this great work ! its really amazing even for 2D plane LIDARs. 

I have a question regarding the usage or not of the intensities information from the lidars in your GICP implementation ? 

Thank you very much !

**Comment by kennyjchen** [comment]
Hi @LotfiZ -- Thanks for the interest in our work. Intensity information is currently used only for visualization in RViz and not explicitly in GICP.

**Comment by LotfiZ** [comment]
Thanks Kenny for your answer ! i'll close the ticket
