### ISSUE TITLE
Catkin_make error with ros noetic running on ubuntu 20.04

### ISSUE THREAD

**Issue by suprio99** [vectr-ucla/direct_lidar_odometry#48]
Hello, I am trying to build the direct Lidar Odometry package after cloning it from the github repo. Here are the steps I followed:

1. Cone the reop using "git clone https://github.com/vectr-ucla/direct_lidar_odometry.git"
2. Install all the dependencies mentioned on the repo's page.
3. Use "catkin_make" in my ros workspace.
The issue:
After 43% of the build is completed, I get an error related to a missing header files namely "save_traj.h"

Can anyone explain what this error is and what could be done to solve it?
Here is a picture of the complete error
![Screenshot from 2024-04-27 13-03-33](https://github.com/vectr-ucla/direct_lidar_odometry/assets/135168448/4faa89ae-6de7-43d3-89ec-d949e7794c9a)
Thank You  

## For anyone facing something similar, the issue might be related to running ROS across a network in multiple systems. For me disconnecting/ closing the host system solved the issue. I tried catkin_make again, and the build was successful.

**Comment by Eku127** [comment]
Hi I met with the same problem, but I am using the docker container to run the ros. Any more specific solution to this problem?

**Comment by arjunskumar** [comment]
@suprio99 try  with `catkin_make -j1`
